### ISSUE TITLE
Issues when using csv_to_txts

### ISSUE THREAD

**Issue by nanoza** [radiolarian/AO3Scraper#11]
Hi there! First, I wanna say thank you so much for building this scraper! I'm extremely new to data scraping (I'm a physicist in training) so this is very helpful in building toy data for a project of mine.

I need individual txt files instead of a single CSV, so I'm trying to use csv_to_txts. However, I run into the following error:
![image](https://user-images.githubusercontent.com/43392363/95685857-80f77d80-0bc8-11eb-824d-5e89bc672cfe.png)

Changing "rb" to "r" in line 29 (apologies if I'm not supposed to do this!) results in this:
![image](https://user-images.githubusercontent.com/43392363/95685934-dfbcf700-0bc8-11eb-9943-386216258f5c.png)

Thanks for your help!

**Comment by ssterman** [comment]
Sorry for the delay; if this is still an issue, can you share the file that you were running that threw the error?
