### ISSUE TITLE
Issues with no kudos

### ISSUE THREAD

**Issue by 71hours** [radiolarian/AO3Scraper#14]
Thanks so much for this scraper! It's awesome. I'm coming across this issue when running ao3_get_fanfics.py where it appears that if the particular work doesn't have kudos, the following error comes up referencing the get_kudos function and ends the program:

![image](https://user-images.githubusercontent.com/75561081/101274642-04fa6a00-37f4-11eb-8109-f26c5a6feb54.png)

This does not appear to be an issue with works that have no bookmarks or no comments.

**Comment by ssterman** [comment]
Should be fixed by https://github.com/radiolarian/AO3Scraper/commit/7f93838c8d528e90e33816009ca08a512fe9cde2; let me know if you run into other problems.
