### ISSUE TITLE
Broken restart feature

### ISSUE THREAD

**Issue by mitchondra** [radiolarian/AO3Scraper#22]
Hello,

when using `--restart` in `ao3_get_fanfics.py` the script crashes.
The reason is missing `lang` argument in the respective call of `write_fic_to_csv` on line 295.

**Comment by AJHoeh** [comment]
It is also missing in line 302. Maybe you could issue a pull request as you already found a solution for another reported issue?

**Comment by ssterman** [comment]
Thanks for the id'ing the problem; should be fixed now by https://github.com/radiolarian/AO3Scraper/commit/a11ba0081126aa2d7d80d14e1b9dc1a6e9fc12f4
