### ISSUE TITLE
429 (and other) status codes not handled

### ISSUE THREAD

**Issue by AJHoeh** [radiolarian/AO3Scraper#24]
When I tried to scrape larger amounts for a NLP Projekt I stumbled over the problem that only a fraction of the ids got scraped. The same has alreay been observed by @celegant in https://github.com/radiolarian/AO3Scraper/issues/20#issuecomment-804780647_

The reason is mainly that there is no catch handling a 429 status code which seems to be returned by ao3 if their security system blocks your ip for around 3 minutes - which happens to me around every 70-100 requets no matter the delay. 
What happens right now is that the scraper will just skip to the next id and so on for the time being blocked by ao3 - which resulted for me in only about 3.5k ids out of 44k requested ids really beeing scraped.

To fix this I implemented status code checks which either write the result of the request to the errorlog (in case of 404 and so on) or in case of 429 wait a certain period of time and then restart scraping at the current id - which is easy to do since the restart functionality is already implemented :)

**Comment by ssterman** [comment]
Sounds like a great fix! Want to make a pull request?

**Comment by AJHoeh** [comment]
@ssterman Sure :) Made a pull request with a minimal invasiv solution
