### ISSUE TITLE
Commas in body causing trouble with CSV

### ISSUE THREAD

**Issue by KMcCloskey12** [radiolarian/AO3Scraper#6]
Hi,

I was able to run ao3_work_ids without problems, but when I use that to scrape the fic bodies, I run into issues where every time a comma appears in the text, the csv reads that as a delimiter. What can I do to fix this? 

Attached is a screenshot: 

<img width="898" alt="csv issues" src="https://user-images.githubusercontent.com/51165726/76105780-a3c31300-5fa3-11ea-8d4d-434eb288b8df.PNG">

Thanks! 

- Kiran

**Comment by ssterman** [comment]
Hi Kiran,

What are you using to open the CSV?  

The fic bodies are enclosed in double quotes ["]  (all actual quotemarks escaped like so [""]), which should mean the commas are considered part of the quoted text.  

You may have to configure the program you use to view the CSV to accept that formatting, however I think Excel and Numbers should both treat it as standard.

**Comment by KMcCloskey12** [comment]
Hi ssterman,

I'm opening the file in Excel, and it turns out the issue isn't the commas, but the large spaces (tabs? line breaks? I have no idea; they appear randomly). But I realized that it's _just_ Excel giving me these problems, and the programs that I actually need for analysis can read it fine, so never mind! 

No idea what's up with Excel, but thanks anyway!
