### ISSUE TITLE
Authors?

### ISSUE THREAD

**Issue by cspenn** [radiolarian/AO3Scraper#7]
Is there a straightforward way to capture author data as well - namely, the name of the author?

**Comment by ssterman** [comment]
Any information rendered on the page can be captured.  In general, inspect the html to find a unique tag that can identify that information, then use the soup.find method to isolate the relevant chunk, and parse out the information you want.  For the author name, you might use the "byline heading" class name on an <h3> tag, which wraps the author username.  

We don't currently support authors, but feel free to build it and make a pull request!

**Comment by bianchi-dy** [comment]
@cspenn I'll be putting up a PR in today for author, kudos and bookmarks.

**Comment by cspenn** [comment]
It's occasions like this that make me regret not learning Python well enough to code in it!

Thank you @bianchi-dy !

**Comment by ssterman** [comment]
closed by https://github.com/radiolarian/AO3Scraper/pull/9
