### ISSUE TITLE
New features for scraping user responses

### ISSUE THREAD

**Issue by bianchi-dy** [radiolarian/AO3Scraper#8]
Hi! First of all, let me say that this scraper was super useful for a project I'm doing on fandom statistics and text. So thank you!

Second of all, I'd like to do a PR that scrapes user-related features such as

- Author name
- Users who have kudoed
- Users who have bookmarked

I've tried to do a PR but it seems I need some sort of special access to create a new branch. Any advice?

**Comment by cspenn** [comment]
Oh, that's sexy. Users who kudos and bookmark could be used to create a KILLER network graph of the most engaged users in a fandom. Damn. Nice job, friend.

**Comment by cspenn** [comment]
Bump, can @ssterman or someone help @bianchi-dy ?

**Comment by ssterman** [comment]
@bianchi-dy I'm glad to hear it was helpful to your project! And I'm excited to get your additions; they sound like great features.  

Can you give us more info on what the message was when you tried to make a PR?  The permissions may be something @radiolarian has to update.

**Comment by radiolarian** [comment]
Thanks for pinging me! Are you first creating a fork to make a PR? By default Github won't let you make a PR on a public project unless you fork it first - https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by bianchi-dy** [comment]
@radiolarian @ssterman have put up the PR https://github.com/radiolarian/AO3Scraper/pull/9
